[package]
name = "image_display"
version = "0.1.0"
edition = "2018"

[profile.dev]
opt-level = 0
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termsize = "0.1"
ctrlc = "3.2.1"
image-convert = "0.11.0"
libc = "0.2.104"
